<script>
  import GlassCard from "./GlassCard.svelte";

  const sentences = [
    "I may not have a castle, but I have a garage",
    "Rally drivers aren't born, they're trained by the fairies of speed.",
    "We don't need a fairy godmother to win, just a turbocharger.",
    "Forget a glass slipper, give me a racing helmet any day.",
    "Who needs a magic wand when you have a steering wheel?",
    "In this story, the hero drives a rally car, not a horse.",
    "Fairy tales have happy endings, but rally races have trophies.",
    "We're not here to find a prince or princess, we're here to find the finish line.",
    "Who needs a fairy tale romance when you have a high-speed chase?",
    "The only magic we need is the power of our engine.",
    "Happily ever after? More like, happily ever after the finish line.",
    "Mirror, mirror on the wall, who's the fastest of them all?",
    "Rally drivers don't kiss frogs, we drift around them.",
    "Forget the seven dwarfs, I just need one mechanic.",
    "The only spells we use in rally are tire rotations and gear changes.",
    "Who needs a genie in a bottle when you have a mechanic in a toolbox?",
    "Fairy tales may have evil queens, but rally has treacherous hairpin turns.",
    "Who needs a magic wand when you have a torque wrench?",
    "Who needs a magic mirror when you have a GPS navigator?",
    "Fairy tales have dragons, but in rally, the only fire-breathing beast is under the hood.",
    "Once upon a time, there was a driver who could parallel park their car faster than Cinderella's fairy godmother could conjure up a dress.",
    "In rally, we debug our code on the road, just like Little Red Riding Hood debugged her path through the forest.",
    "Once upon a time, there was a co-driver who could navigate through the most complex algorithms with ease.",
    "Just like in a fairy tale, the rally was full of surprises and unexpected twists.",
    "The checkpoints were like pieces of a puzzle, and we had to put them together to find our way to the finish line.",
  ];
</script>

<GlassCard header="Quote">
  <blockquote class="blockquote mb-0">
    <p>
      {sentences[Math.floor(Math.random() * sentences.length)]}
    </p>
    <footer class="blockquote-footer">
      Generated by <cite title="Source author">ChatGPT</cite>
    </footer>
  </blockquote>
</GlassCard>
