<script>
  import GlassCard from "./GlassCard.svelte";

  const sentences = [
    "Life is like Rainbow Road—full of twists, turns, and vibrant colors. Embrace every curve with pride!",
    "Just like Rainbow Road, our journey is unique and colorful. Drive with pride and celebrate every moment.",
    "In the race of life, remember to stay true to your colors. Every lap on Rainbow Road is a step closer to pride and acceptance.",
    "On Rainbow Road, everyone is a winner. Celebrate your journey, your identity, and your pride.",
    "No matter how challenging the road, remember that every color in the rainbow is a testament to your strength and pride.",
    "Life may throw banana peels and blue shells your way, but with pride in your heart, you'll always cross the finish line on Rainbow Road.",
    "Just as Rainbow Road glows with every hue, let your true colors shine brightly with pride.",
    "On Rainbow Road, diversity is celebrated, and love always wins. Drive forward with pride and joy.",
    "Every twist and turn on Rainbow Road brings us closer to unity and acceptance. Embrace the journey with pride.",
    "Like a star in Mario Kart, let your pride power you through the toughest races on Rainbow Road.",
    "Rainbow Road teaches us that the path to victory is colorful and diverse. Celebrate your unique journey with pride.",
    "In the spirit of Rainbow Road, let's celebrate our individuality and pride, making every race a joyous ride.",
    "As you race down Rainbow Road, remember that each color represents a story of courage, love, and pride.",
    "Life's Rainbow Road is filled with vibrant moments. Embrace each one with pride and keep moving forward.",
    "On Rainbow Road, the journey is just as important as the destination. Celebrate every colorful step with pride.",
    "Every race on Rainbow Road is a reminder that our true colors make us stronger and more united. Drive with pride.",
    "Rainbow Road is a symbol of endless possibilities. Let your pride guide you to new and exciting destinations.",
    "In the game of life, Rainbow Road reminds us that our differences make us beautiful. Celebrate with pride.",
    "Just as every racer shines on Rainbow Road, let your pride shine brightly in every aspect of your life.",
    "Rainbow Road is a testament to the beauty of diversity. Embrace your uniqueness and celebrate with pride."
  ];
</script>

<GlassCard header="Quote">
  <blockquote class="blockquote mb-0">
    <p>
      {sentences[Math.floor(Math.random() * sentences.length)]}
    </p>
    <footer class="blockquote-footer">
      Generated by <cite title="Source author">ChatGPT</cite>
    </footer>
  </blockquote>
</GlassCard>
